### ISSUE TITLE
Automatic origin setting 

### ISSUE THREAD

**Issue by Pallav1299** [ctu-mrs/mrs_uav_managers#13]
Hey @klaxalk,

I can see that the origin is fixed in "world_origin.yaml". Am I right? 

Is there a mechanism to automatically initialize it in case of GPS estimator availability?

Thanks

**Comment by petrlmat** [comment]
Hi @Pallav1299 ,
there is no mechanism to initialize it automatically. We use the world_origin.yaml to define our origin of the local "world" we want to fly in so we want to have manual control over it.
