### ISSUE TITLE
Estimator reset handling and generic estimator design

### ISSUE THREAD

**Issue by Pallav1299** [ctu-mrs/mrs_uav_managers#14]
Hey @klaxalk, I hope I'm not overwhelming you with too many questions recently.

I could understand from code that custom estimator plugins handle Soft Resets via implementation in StateGeneric. Are you able to handle estimator Hard Resets(estimator outpur reinitializes from 0) as well? If yes, could you help me know how? 

Thanks

**Comment by petrlmat** [comment]
Hi @Pallav1299 ,
estimator reset is possible but there should be another estimator that can be used for feedback control while the reset is in progress. E.g. you want to reset your VIO estimator, so you should have a second estimator (for example LIO or GPS) that can be used during the reset. If there is no other estimator, the UAV cannot be stabilized and will perform a failsafe land (gradual decrease of thrust while keeping horizontal attitude using IMU data only).
